version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/droplater
      - REDIS_URL=redis://redis:6379
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - PORT=3000
    depends_on:
      - mongo
      - redis
    volumes:
      - ./api:/app/api
      - ./admin:/app/admin
    command: npm run dev:api

  worker:
    build: .
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/droplater
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    volumes:
      - ./worker:/app/worker
    command: npm run dev:worker

  sink:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - PORT=4000
      - SINK_FAILURE_RATE=${SINK_FAILURE_RATE:-0}
    depends_on:
      - redis
    volumes:
      - ./sink:/app/sink
    command: npm run dev:sink

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=droplater

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
